arb-dir: lib/logic/client/localization
template-arb-file: app_en.arb
untranslated-messages-file: lib/logic/client/localization/untranslated.txt
output-localization-file: app_localizations.dart
nullable-getter: false