name: allo
description: Chat app
publish_to: 'none'
version: 0.0.5+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cloud_firestore: ^1.0.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+2
  image_picker: ^0.7.4
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
