name: allo
description: Chat app
publish_to: 'none'
version: 1.3.0+147

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  awesome_notifications: ^0.0.6+10
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  fluentui_system_icons: ^1.1.136
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  in_app_update: ^2.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  fonts:
    - family: GS-Text
      fonts:
        - asset: fonts/GS-Text-Regular.ttf
        - asset: fonts/GS-Text-Bold.ttf
          weight: 700
        - asset: fonts/GS-Text-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/GS-Text-Medium.ttf
          weight: 500
        - asset: fonts/GS-Text-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/GS-Text-Italic.ttf
          style: italic 
    
