name: allo
description: Chat app
publish_to: 'none'
version: 1.3.5+312

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.3
  awesome_notifications: #^0.7.0 once stable
    git:
      ref: "bd5dfeb"
      url: https://github.com/rafaelsetragni/awesome_notifications
  animated_progress:
    git: https://github.com/iamcosmin/animated_progress
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.15
  device_info_plus: ^4.0.0
  dynamic_color: ^1.4.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_remote_config: ^2.0.7
  firebase_storage: ^10.2.16
  firebase_image:
    path: ./packages/firebase_image
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.0.0-dev.7
  http: ^0.13.4
  image_cropper: ^2.0.2
  image_picker: ^0.8.5+3
  # in_app_update: ^2.0.0 // Some bugs do not permit for this to run. We will remove it temporarily as it is not used either.
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  material_color_utilities: ^0.1.4
  shimmer: ^2.0.0
  sliver_tools: ^0.2.7
  flutter_staggered_animations: ^1.0.0
  snap_scroll_physics: ^0.0.1+3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/Jakarta-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Jakarta-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Jakarta-Light.ttf
          weight: 300
        - asset: assets/fonts/Jakarta-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Jakarta-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jakarta-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Jakarta-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jakarta-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Jakarta-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jakarta-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Jakarta-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jakarta-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Jakarta-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jakarta-ExtraBoldItalic.ttf
          weight: 800
          style: italic


flutter_intl:
  enabled: true
  main_locale: en
