name: allo
description: Chat app
publish_to: 'none'
version: 0.0.8+46

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.1
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  flutter_hooks: ^0.17.0
  flutter_local_notifications: ^6.0.0
  hooks_riverpod: ^0.14.0+4
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
