name: allo
description: Chat app
publish_to: 'none'
version: 1.3.4+288

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  awesome_notifications: #^0.7.0 once stable
    git:
      ref: "05ffe54"
      url: https://github.com/rafaelsetragni/awesome_notifications
  animated_progress:
    git: https://github.com/iamcosmin/animated_progress
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.15
  device_info_plus: ^3.2.3
  dynamic_color: ^1.2.2
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  firebase_remote_config: ^2.0.7
  firebase_storage: ^10.2.16
  firebase_image:
    path: ./packages/firebase_image
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.0.0-dev.7
  http: ^0.13.4
  image_cropper: ^2.0.2
  image_picker: ^0.8.5+3
  # in_app_update: ^2.0.0 // Some bugs do not permit for this to run. We will remove it temporarily as it is not used either.
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  flutter_native_splash: ^2.1.5
  material_color_utilities: ^0.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Text
      fonts:
        - asset: fonts/text/regular.ttf
        - asset: fonts/text/italic.ttf
          style: italic
        - asset: fonts/text/bold.ttf
          weight: 700
        - asset: fonts/text/bold-italic.ttf
          weight: 700
          style: italic
        - asset: fonts/text/medium.ttf
          weight: 500
        - asset: fonts/text/medium-italic.ttf
          weight: 500
          style: italic
    - family: Display
      fonts:
        - asset: fonts/display/regular.ttf
        - asset: fonts/display/italic.ttf
          style: italic
        - asset: fonts/display/bold.ttf
          weight: 700
        - asset: fonts/display/bold-italic.ttf
          weight: 700
          style: italic
        - asset: fonts/display/medium.ttf
          weight: 500
        - asset: fonts/display/medium-italic.ttf
          weight: 500
          style: italic
flutter_intl:
  enabled: true
  main_locale: en
