name: allo
description: Chat app
publish_to: 'none'
version: 1.1.0+108

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  awesome_notifications: ^0.0.6+10
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  fluentui_system_icons: ^1.1.136
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  in_app_update: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  fonts:
    - family: VarDisplay
      fonts:
        - asset: fonts/Variable-Display.ttf
        - asset: fonts/Variable-Display-Bold.ttf
          weight: 700
        - asset: fonts/Variable-Display-Light.ttf
          weight: 300
        - asset: fonts/Variable-Display-Semibold.ttf
          weight: 600
