name: allo
description: Chat app
publish_to: 'none'
version: 1.3.2+158

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  awesome_notifications: ^0.6.20
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  fluentui_system_icons: ^1.1.153
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  in_app_update: ^2.0.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  fonts:
    - family: GS-Text
      fonts:
        - asset: fonts/GS-Text-Regular.ttf
        - asset: fonts/GS-Text-Bold.ttf
          weight: 700
        - asset: fonts/GS-Text-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/GS-Text-Medium.ttf
          weight: 500
        - asset: fonts/GS-Text-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/GS-Text-Italic.ttf
          style: italic 
    
