name: Build alpha

on: 
  push: 
   branches:
    - alpha

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Setup
      uses: actions/checkout@v1
    - name: Java Setup
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter Setup
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Expand keystore
      run: |
           cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > app/release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: Play Store - Build
      run: | 
          flutter build appbundle --flavor prod
    - name: Play Store - Release
      uses: r0adkll/upload-google-play@v1.0.15
      with: 
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SECURITY_KEY }}
        packageName: com.relays.messenger
        releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
        track: alpha
        whatsNewDirectory: distribution
    - name: Publish Release Notes
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_CHANNEL }}
        token: ${{ secrets.TELEGRAM_BOT_ID }}
        format: markdown
        message: "alpha ${{ github.event.head_commit.message }}\nActualizarea este dispoibilă în Magazin Play pentru cei din canalul alpha."