name: Build Allo

on: 
  push: 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Prepare packages
      run: flutter pub get
    - name: Keystore expansion
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
           cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > app/release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: Build Android
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: | 
          flutter build apk --split-per-abi
          flutter build appbundle
          cd build/app/outputs/bundle/release
          mv app-release.aab ../../apk/release/Allo_appbundle.aab
          cd ../../apk/release
          mv app-arm64-v8a-release.apk Allo_arm64.apk
          mv app-armeabi-v7a-release.apk Allo_arm7.apk
          mv app-x86_64-release.apk Allo_x86.apk
          rm -rf app-arm64-v8a-release.apk
          rm -rf app-armeabi-v7a-release.apk
          rm -rf app-x86_64-release.apk
    - name: Upload Android Release
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v1
      with: 
        name: Allo_Release
        path: build/app/outputs/apk/release/
    - name: Build web
      run: flutter build web --web-renderer canvaskit
    - name: Deploy web
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALLO_MS }}'
        projectId: allo-ms
        channelId: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels