name: Build release

on: 
  push: 
   branches:
    - main

jobs:
  build_android: 
    runs-on: ubuntu-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Download packages
      run: flutter pub get
    - name: Prepare keystore
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
           cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > app/release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: Build
      if:   github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: | 
          flutter build apk --split-per-abi
          flutter build appbundle
          cd build/app/outputs/bundle/release
          mv app-release.aab ../../apk/release/Allo_appbundle.aab
          cd ../../apk/release
          mv app-arm64-v8a-release.apk Allo_arm64.apk
          mv app-armeabi-v7a-release.apk Allo_arm7.apk
          mv app-x86_64-release.apk Allo_x86.apk
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "New release"
        files: |
              build/app/outputs/apk/release/Allo_appbundle.aab
              build/app/outputs/apk/release/Allo_arm64.apk
              build/app/outputs/apk/release/Allo_arm7.apk
              build/app/outputs/apk/release/Allo_x86.apk
    
  build_web:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v1
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Download packages
      run: flutter pub get
    - name: Build
      run: flutter build web --web-renderer canvaskit
    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALLO_MS }}'
        projectId: allo-ms
        channelId: live
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
