name: Deploy Stable

on: 
  push: 
   branches:
    - stable
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Setup - Checkout
      uses: actions/checkout@v3
    - name: Setup - Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
    - name: Setup - Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
    - name: Setup - Signing
      run: |
           cd android/
           echo "${{ secrets.KEYSTORE }}" > release.jks.asc
           gpg -d --passphrase "${{ secrets.PASS_PHRASE }}" --batch release.jks.asc > app/release.jks
           echo "${{ secrets.KEYSTORE_PASS }}" > key.properties
           cd ..
    - name: Web - Build
      run: |
          flutter build web
    - name: Web - Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALLO_MS }}'
        projectId: allo-ms
        channelId: live
        target: stable
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
